### ISSUE TITLE
Support for Svelte key blocks

### ISSUE THREAD

**Issue by ruairi-ppr** [corneliusio/svelte-sublime#10]
I've started using the new Svelte feature, [key blocks](https://svelte.dev/docs#key), but notice that the syntax highlighting fails when I use them. I suppose it's just because it's a fairly new feature but would be good to have the syntax support as all my components are hard to read now - I'm using key blocks all over the place.
Cheers!

**Comment by corneliusio** [comment]
Thanks for pointing this out! Didn't know it had been added—will get support for it pushed as soon as possible.

**Comment by corneliusio** [comment]
Support added in the current release. Package Control may take a bit to update but the update should be availble in the next day or so.
