### ISSUE TITLE
Support lang="ts"

### ISSUE THREAD

**Issue by nickhstr** [corneliusio/svelte-sublime#11]
With much of the Svelte docs suggesting the `lang="ts"` script attribute, it'd be great to have that added to `script-lang-decider`.

**Comment by corneliusio** [comment]
Ha, knew this would come back to haunt me. Actually opened [an issue](https://github.com/sveltejs/svelte/issues/2719) about it a little over a year ago to get some direction, but there was never anything explicitly landed on and, at the time, most examples used the `[type]` attribute.

Does sound like `[lang]` should be added though.

**Comment by corneliusio** [comment]
Support added in the current release—you can now either use `type="text/ts"` or `lang="ts"`. Package Control may take a bit to update but the update should be available in the next day or so.

**Comment by nickhstr** [comment]
That's great, thank you for the update!
