### ISSUE TITLE
no luck using `<style lang=less>`

### ISSUE THREAD

**Issue by loveencounterflow** [corneliusio/svelte-sublime#12]
When I use `<style lang=less>` or `<style type=text/less>` all I get is white text with—curiously—*some* autocompletion (for property names, but not values). 

When I mark the block in an arbitrary fashion as in `<style type=xxx>`, I get full support for CSS. 

I do have https://packagecontrol.io/packages/LESS installed, is that the correct one? Could it be any other package as long as it supports Less syntax?

**Comment by corneliusio** [comment]
Thanks for bringing this up. Looks like there was an issue specifically with LESS—at some point the scope name for the package was tweaked a little bit. I've just pushed a fix that should get it working again. That LESS package is the one that I've used and it's working on my end now so update should be available in the next day or so on Package Control clear up this issue.

**Comment by loveencounterflow** [comment]
Thanks a bunch for the lightning-fast response! I'll be back shortly with a report on whether it works.

**Comment by loveencounterflow** [comment]
Just upgraded to v3.4.1 and—seems to work. Yay! Thx a bunch, closing this one!
