### ISSUE TITLE
markup syntax (pug)

### ISSUE THREAD

**Issue by dartheian** [corneliusio/svelte-sublime#13]
Hi, would it be possible to add pug markup syntax highlighting?

**Comment by corneliusio** [comment]
Hey! Thanks for the suggestion. This has come up before and ultimately I've opted not to add pug support to this package. You can read my full reasoning for that decision **[here](https://github.com/corneliusio/svelte-sublime/issues/9#issuecomment-706600323)**.

**Comment by dartheian** [comment]
Oh my, I forgot to search into closed issues... Thanks for the reply, you've got a point.
