### ISSUE TITLE
Scopes break when binding events to a component

### ISSUE THREAD

**Issue by ccampbell** [corneliusio/svelte-sublime#16]
I just started noticing this recently and tested in safe mode in Sublime Text 4. You can see here:

<img src="https://user-images.githubusercontent.com/259316/136616992-cf4367c0-a9df-4fb8-8d14-d0f9cea2c664.png" width="605" height="93" />

Please let me know if you need any more information. It looks like it starts with the first closing bracket `}` which is scoped as `invalid.illegal.stray-bracket-end.js`

I am happy to take a look at fixing it myself too, but figured I would open up an issue here since you may know exactly what the issue is. Thanks!

**Comment by easyfrog** [comment]
I have same issue, could you tell me how you fix it?

**Comment by ilokhov** [comment]
Seeing the same issue, specifically after updating Sublime Text to Build 4121. The change to cause this might have happened in [dev Build 4114 which mentions "Various syntax highlighting improvements" in the changelog](https://www.sublimetext.com/dev).

**Comment by ccampbell** [comment]
I actually have a fix for this. Will try to clean it up and send a PR later today.

**Comment by wmstens** [comment]
It sounds like the original dev is busy. Do you have the fix ironed out @ccampbell?  Sorry to bug.

**Comment by ccampbell** [comment]
@wmstens just opened a pull request. Feel free to try out my fork. #18

**Comment by wmstens** [comment]
I just sideloaded this fork and it seems to work for me. Thanks a bunch!

**Comment by corneliusio** [comment]
Noting here, I've started working on some fixes that are in the https://github.com/corneliusio/svelte-sublime/tree/v4 branch. There are still some issues, but it's far less broken than the current release. Feel free to manually install while I finish up some of the smaller fixes.

I'm also going to lock convo on this issue in favor of #17 to tidy things up a bit, will leave this open till resolved though for reference.

**Comment by corneliusio** [comment]
Should now be fixed with v3.5.0.
