### ISSUE TITLE
How to style "if, else, var, const..." with special characters, as in the "hello-world-3.png screenshot

### ISSUE THREAD

**Issue by H34Dlezman** [corneliusio/svelte-sublime#27]

**Comment by H34Dlezman** [comment]
Hey there
first thanks for the Svelte Syntax highlighting! 😄
I really like the way the if, const.. etc. are displayed in your editor in that screenshot "hello-world-3.png".

Can you briefly say how that can be done?

Cheers!

**Comment by corneliusio** [comment]
@H34Dlezman Hey, thanks! Just to be clear, are you asking about theme/colors specifically? Or are you not seeing any syntax highlighting at all in your Svelte files?

**Comment by H34Dlezman** [comment]
Hey @corneliusio, exactly, I mean the theme used in the screenshot, displaying the "if, else etc." in that cool font.
The svelte syntaxing works perfectly fine.

Thanks!

**Comment by corneliusio** [comment]
@H34Dlezman Cool cool. The font is Operator Mono, it's a premium font but if you want to spring for it you can find it [here](https://www.typography.com/fonts/operator/overview).

If you're wanting the color scheme as well, it's one I put together myself (though I think it's really similar to another color scheme that was really popular for a while). This theme is for Sublime Text, but if you need it for VSCode I'd wager there are some tools out there for converting it to a VSCode theme.
[Canister.sublime-color-scheme.zip](https://github.com/corneliusio/svelte-sublime/files/9234834/Canister.sublime-color-scheme.zip)

**Comment by H34Dlezman** [comment]
thanks a lot @corneliusio! awesome font ✌🏽

**Comment by corneliusio** [comment]
No problem!
