### ISSUE TITLE
3.6 broken

### ISSUE THREAD

**Issue by ildella** [corneliusio/svelte-sublime#32]
Right after upgrade, I get this error and there is no syntax highlight anymore in .svelte files. 

Is there a simple way I can downgrade to 3.5.x until this is resolved? Thanks.

```
error: Error loading syntax file "Packages/Svelte/Svelte.sublime-syntax": Apparent recursion within a with_prototype action: 25000 context sanity limit hit
```

**Comment by corneliusio** [comment]
@ildella This has been fixed, I'll have a PR to get this update in Package Control this weekend.

**Comment by ildella** [comment]
already installed from github the new version, works perfectly!
