### ISSUE TITLE
cpu usage peaks when plugin enabled

### ISSUE THREAD

**Issue by spooky** [corneliusio/svelte-sublime#4]
When I open a dir with a baseline svelte project (npx degit sveltejs/template my-svelte-project) in sublime, CPU usage jumps to 100% and stays that way.

Log from sublime:
```
worker 7996 appears stuck while processing file (...)/node_modules/rollup/dist/rollup.es.js, killing process
worker 8020 appears stuck while processing file (...)/node_modules/rollup/dist/rollup.js, killing process
```

**Comment by corneliusio** [comment]
Sorry, but this is not an issue related to this package. This repo is solely syntax definitions for `.svelte` files. It wouldn't even touch a `rollup.config.js`. 

Edit: Should mention that I did step through the repro just to make sure. This is likely an issue with some Javascript related plugin you have enabled.

**Comment by spooky** [comment]
Issue stops as soon as I uninstall the plugin so there's a big chance it's not a different one that I have enabled.

**Comment by corneliusio** [comment]
I’ll do a bit of digging to make sure, but that error tends to be related to a corrupt index cache in Sublime. I certainly believe that the issue is only occurring when this package is enabled, but it’s not necessarily due to a bug in this package or anything I’ll be able to fix.
